### ISSUE TITLE
feed is added three times per once

### ISSUE THREAD

**Issue by who-am-1** [teddy-gustiaux/youtube-rss-finder#2]
I open via liferea-add-feed in Firefox and feed is added three times per once. But in terminal it's add feed only once. It's firefox bug or this extension?

**Comment by teddy-gustiaux** [comment]
Thanks for opening an issue! The add-on does not handle RSS subscriptions (it only opens the feed itself in a new tab), so this problem is likely to be related to the tool you are using to manage your RSS subscriptions.

I would recommend to see if the developers of this tool are able to help you. I am going to close this issue for now, but if it appears to be a problem related with the add-on itself, feel free to reopen it. 🙂

**Comment by who-am-1** [comment]
can't reproduce with 1.0.2

**Comment by teddy-gustiaux** [comment]
That is a good news!
